version: 2
updates:
  # Dependency notifications for vendored libraries
  - package-ecosystem: "nuget"
    directory: "/honeypot"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:vendors"
  # Src libraries
  - package-ecosystem: "nuget"
    directory: "/src/Datadog.Trace"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:tracer"
  - package-ecosystem: "nuget"
    directory: "/src/Datadog.Trace.ClrProfiler.Managed"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:integrations"
    ignore:
      # AspNetCore reference libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "Microsoft.AspNetCore.Hosting.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Mvc.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Routing"

      # DuckTyping libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "System.Reflection.Emit"
      - dependency-name: "System.Reflection.Emit.Lightweight"

  - package-ecosystem: "nuget"
    directory: "/src/Datadog.Trace.OpenTracing"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:opentracing"
  - package-ecosystem: "nuget"
    directory: "/src/Datadog.Trace.BenchmarkDotNet"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:benchmarks"
