version: '3'
services:
  redis:
    image: redis:4-alpine
    command: redis-server --bind 0.0.0.0
    ports:
    - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
    - discovery.type=single-node

  build:
    build:
      context: ./
      dockerfile: ./docker/dotnet.dockerfile
    image: datadog-dotnet
    command: /project/docker/build.sh
    volumes:
    - ./:/project

  Datadog.Trace.ClrProfiler.Native:
    build:
      context: ./
      dockerfile: ./docker/native.dockerfile
    image: datadog-native
    command: bash -c "cd /project/src/Datadog.Trace.ClrProfiler.Native/ && mkdir -p obj/Debug/x64 && cd obj/Debug/x64 && cmake ../../.. && make"
    volumes:
    - ./:/project

  Samples.ConsoleCore:
    image: microsoft/dotnet:2.1-sdk
    command: bash -c "mkdir -p /var/log/datadog ; /project/docker/with-profiler.bash dotnet /project/samples/Samples.ConsoleCore/bin/Release/netcoreapp2.0/publish/Samples.ConsoleCore.dll ; cat /var/log/datadog/dotnet-profiler.log"
    volumes:
    - ./:/project

  Samples.RedisCore:
    build:
      context: ./
      dockerfile: ./docker/dotnet.dockerfile
    image: datadog-dotnet
    command: bash -c "mkdir -p /var/log/datadog ; wait-for-it redis:6379 -- /project/docker/with-profiler.bash dotnet /project/samples/Samples.RedisCore/bin/Release/netcoreapp2.0/publish/Samples.RedisCore.dll ; cat /var/log/datadog/dotnet-profiler.log"
    volumes:
    - ./:/project
    environment:
    - REDIS_HOST=redis
    depends_on:
    - redis

  Samples.Elasticsearch:
    build:
      context: ./
      dockerfile: ./docker/dotnet.dockerfile
    image: datadog-dotnet
    command: bash -c "mkdir -p /var/log/datadog ; wait-for-it redis:6379 -- /project/docker/with-profiler.bash dotnet /project/samples/Samples.Elasticsearch/bin/Release/netcoreapp2.0/publish/Samples.Elasticsearch.dll ; cat /var/log/datadog/dotnet-profiler.log"
    volumes:
    - ./:/project
    environment:
    - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
    - elasticsearch

  Datadog.Trace.ClrProfiler.IntegrationTests:
    build:
      context: ./
      dockerfile: ./docker/dotnet.dockerfile
    image: datadog-dotnet
    command: bash -c "mkdir -p /var/log/datadog ; wait-for-it redis:6379 -- dotnet test /project/test/Datadog.Trace.ClrProfiler.IntegrationTests/Datadog.Trace.ClrProfiler.IntegrationTests.csproj  ; cat /var/log/datadog/dotnet-profiler.log"
    volumes:
    - ./:/project
    environment:
    - REDIS_HOST=redis
    depends_on:
    - redis
