version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build projects
          command: |
            make build
      - run:
          name: Build native
          command: |
            make native
