version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run:
        name: Build projects
        command: |
          docker-compose run build
    - run:
        name: Build native
        command: |
          docker-compose run Profiler
    - run:
        name: Run integration tests
        command: |
          docker-compose run Datadog.Trace.ClrProfiler.IntegrationTests
    - run:
        name: Package for linux
        command: |
          docker-compose run package
    - store_artifacts:
        path: ./deploy/linux
