version: 2
jobs:
  build:
    docker:
      - image: datadog/docker-library:ddtrace_csharp_0_1_1
      - image: datadog/docker-dd-agent
        env:
          - DD_APM_ENABLED=true
          - DD_BIND_HOST=0.0.0.0
          - DD_API_KEY=invalid_key_but_this_is_fine
      - image: microsoft/mssql-server-linux:2017-CU3
        env:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=password!123
    steps:
      - checkout
      - run:
          name: Run clang-format
          command: |
            find ./ -iname *.h -o -iname *.cpp | while read fname; do 
              changes=$(clang-format-6.0 -output-replacements-xml $fname | grep -c "<replacement " || true)
              if [ $changes != 0 ]
              then
                clang-format-6.0 -output-replacements-xml $fname
                echo "$fname did not pass clang-format, consider running: find ./ -iname *.h -o -iname *.cpp | xargs clang-format-6.0 -i"
                exit 1
              fi
            done
      - run: git submodule init
      - run: git submodule update
      - run: ./build.sh
