version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/build-image
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t coreclr:latest .
      - run:
          name: Build projects
          command: |
            make build
      - run:
          name: Build native
          command: |
            make native
      - run:
          name: Run integration tests
          command: |
            make Datadog.Trace.ClrProfiler.IntegrationTests
