trigger: none
pr: none

variables:
  buildConfiguration: release
  dotnetCoreSdkVersion: 5.0.103
  ddApiKey: $(DD_API_KEY)
  publishOutput: $(Build.SourcesDirectory)/tracer/bin/managed-publish

# Declare the datadog agent as a resource to be used as a pipeline service
resources:
  containers:
  - container: dd_agent
    image: datadog/agent
    ports:
    - 8126:8126
    env:
      DD_API_KEY: $(ddApiKey)
      DD_INSIDE_CI: true

stages:
- stage: build
  jobs:

  #### Windows 

  - job: Windows
    pool: Benchmarks
    
    workspace:
      clean: all

    # Enable the Datadog Agent service for this job
    services:
      dd_agent: dd_agent
    variables:
      tracerHomeName: windows-tracer-home
      tracerHome: $(System.DefaultWorkingDirectory)/tracer/bin/$(tracerHomeName)
      msiHome: $(System.DefaultWorkingDirectory)/tracer/bin/msi
      nuget_packages: $(Pipeline.Workspace)/.nuget/packages

    steps:

    - task: UseDotNet@2
      displayName: install dotnet core sdk
      inputs:
        packageType: sdk
        version: $(dotnetCoreSdkVersion)

    - task: NuGetToolInstaller@1
      displayName: install nuget

    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: tracer/src/**/*.csproj

    # native projects must be restored with nuget.exe
    - task: NuGetCommand@2
      displayName: nuget restore native
      inputs:
        restoreSolution: Datadog.Trace.Native.sln
        verbosityRestore: Normal

    - task: DotNetCoreCLI@2
      displayName: Benchmarks
      inputs:
        command: 'run'
        projects: '$(System.DefaultWorkingDirectory)/tracer/test/benchmarks/Benchmarks.Trace/Benchmarks.Trace.csproj'
        arguments: '-c Release -f netcoreapp3.1 -- -r net472 netcoreapp3.1 -m -f * --iterationTime 1500'
      env:
        DD_ENV: CI
        DD_SERVICE: dd-trace-dotnet

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Start-Sleep -s 120'