trigger:
  batch: 'true'
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - docs/*
      - .github/*

variables:
  buildConfiguration: debug
  packageFeed: /ffc32c57-3e0e-4e8f-8633-a7ad01df2e45

jobs:

- job: linux

  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: DockerCompose@0
    displayName: docker-compose run build
    inputs:
      containerregistrytype: Container Registry
      dockerComposeCommand: run -e TestAllPackageVersions=true build

  - task: DockerCompose@0
    displayName: docker-compose run Datadog.Trace.ClrProfiler.Native
    inputs:
      containerregistrytype: Container Registry
      dockerComposeFileArgs: TestAllPackageVersions=true
      dockerComposeCommand: run Datadog.Trace.ClrProfiler.Native

  - task: DockerCompose@0
    displayName: docker-compose run Datadog.Trace.ClrProfiler.IntegrationTests
    inputs:
      containerregistrytype: Container Registry
      dockerComposeCommand: run -e TestAllPackageVersions=true Datadog.Trace.ClrProfiler.IntegrationTests

  - task: PublishTestResults@2
    displayName: publish test results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: test/**/*.trx
    condition: succeededOrFailed()
