trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
      - .github/*
pr:
  branches:
    include:
      - master
      - release/*
  paths:
    exclude:
      - docs/*
      - .github/*

pool:
  vmImage: ubuntu-18.04

variables:
  buildConfiguration: Debug
  publishOutput: $(System.DefaultWorkingDirectory)/src/bin/managed-publish
  dotnetCoreSdkVersion: 3.1.107

jobs:

- job: Windows
  timeoutInMinutes: 80
  strategy:
    matrix:
      x64:
        buildPlatform: x64
        enable32bit: false
      x86:
        buildPlatform: x86
        enable32bit: true
  pool:
    vmImage: windows-2019
  variables:
    msiOutputDirectory: deploy/Datadog.Trace.ClrProfiler.WindowsInstaller/bin/$(buildConfiguration)/$(buildPlatform)/en-us

  steps:
  - task: UseDotNet@2
    displayName: install dotnet core sdk 2.1
    inputs:
      packageType: sdk
      version: 2.1.x