pool:
  name: Hosted VS2017 # TODO: upgrade C++ projects and change this to "Hosted Windows 2019 with VS2019"
  demands: msbuild

strategy:
  matrix:
    x64_Debug:
      BuildPlatform: 'x64'
      BuildConfiguration: 'Debug'
    x86_Debug:
      BuildPlatform: 'x86'
      BuildConfiguration: 'Debug'
    
steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'Datadog.Trace.Native.sln'
    vstsFeed: '/ffc32c57-3e0e-4e8f-8633-a7ad01df2e45'
    verbosityRestore: Normal

- task: MSBuild@1
  displayName: 'Build C++ DLL and tests (x64 or x86)'
  inputs:
    solution: Datadog.Trace.proj
    msbuildArchitecture: x64
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:BuildCpp;BuildCppTests'
    maximumCpuCount: true

- script: 'Datadog.Trace.ClrProfiler.Native.Tests.exe --gtest_output=xml'
  workingDirectory: '$(System.DefaultWorkingDirectory)/test/Datadog.Trace.ClrProfiler.Native.Tests/bin/$(BuildConfiguration)/$(BuildPlatform)'
  displayName: 'Run C++ unit tests'

- task: PublishTestResults@2
  displayName: 'Publish C++ Test Results'
  inputs:
    testResultsFiles: 'test/**/test*.xml'
    buildPlatform: '$(BuildPlatform)'
    buildConfiguration: '$(BuildConfiguration)'
  condition: succeededOrFailed()
